services:
  web:
    build:
      target: development
    # volumes:
    #   - ./apps/web:/app/apps/web
    #   - ./package.json:/app/package.json
    #   - ./package-lock.json:/app/package-lock.json
    #   - /app/node_modules
    #   - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development

  admin:
    build:
      target: development
    volumes:
      - ./apps/admin:/app/apps/admin
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
      - /app/apps/admin/node_modules
    environment:
      - NODE_ENV=development
