# Production Docker Compose - GHCR 이미지 사용
# 사용법: docker compose -f compose.prod.yml up -d

services:
  # Web Application (GHCR에서 pull)
  web:
    image: ${ANGPLE_WEB_IMAGE:-ghcr.io/angple/angple-web:latest}
    container_name: angple-web
    ports:
      - "${WEB_PORT:-3010}:3000"
    restart: unless-stopped
    networks:
      - angple-network
      - proxy-network
      - backend_angple-network
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://angple-api:8081/api/v2
      - NODE_OPTIONS=--max-old-space-size=512

networks:
  angple-network:
    external: true
  proxy-network:
    external: true
  backend_angple-network:
    external: true
